VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "ClsGLOther"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Public FlgVat As Integer
Public Vatyo As Double
Public Vat As Double
Public AccountCode2 As String
Public CurrRow As Integer
Public UnitString As String
Public Unitss As String
Public TotalValue As Double
Public SupplierID As Integer
Public CusVATNO As String
Public SupplierName As String
Public PriceTotal As Double
Public Rate As Double
Public DescAccount As String
Public NextAccount_Code As String





